# Generated by Django 3.2 on 2022-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=150)),
                ('sales_number', models.PositiveIntegerField()),
                ('revenue', models.FloatField()),
            ],
        ),
    ]
